### ISSUE TITLE
vstack not working?

### ISSUE THREAD

**Issue by CesMak** [QQuick/Numscrypt#4]
I just tried:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.vstack((a,b)))

what it should give is:
array([[1, 2, 3],
       [2, 3, 4]])

instead i get:
[
	[]
	[]
	[]
	[]
	[]
	[]
]

My imports are:
 Imports:
```
from org.transcrypt.stubs.browser import *
from org.transcrypt.stubs.browser import __main__, __envir__, __pragma__
from itertools import chain
import math

# Imports for Transcrypt, skipped runtime by CPython
if __envir__.executor_name == __envir__.transpiler_name:
	import numscrypt as num

# Imports for CPython, skipped compile time by Transcrypt
__pragma__ ('skip')
import numpy as num  # -> list of functions: https://transcrypt.org/numscrypt/docs/html/supported_constructs.html
__pragma__ ('noskip')
```

AM I missing something?

**Comment by JdeH** [comment]
Hi,

vstack is in  the autotest:

https://github.com/QQuick/Numscrypt/blob/master/numscrypt/development/automated_tests/ndarray/basics/__init__.py

line 89 and 96

So it should work, no idea yet what the problem comes from.
It could be that it's somehow broken in conjunction with using new TS versions.
We'll take a look at it at first opportunity.

There could also be other problems.
Working with ndarrays generally needs operator overloading (opov pragma).

http://www.transcrypt.org/docs/html/special_facilities.html#operator-overloading-pragma-opov-and-pragma-noopov

You can take a look at the file given by the link above to see what's required.
Maybe it will help, otherwise please await the bugfix.

Kind regards
Jacques
